FROM python:3.11-slim

# set the working directory
WORKDIR /app

# copy the requirements file into the container at /app
COPY requirements.txt requirements.txt
COPY data/requirements-data.txt data/requirements-data.txt

# update pip and install dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
    # pip install -r data/requirements-data.txt

# copy the current directory contents into the container at /app
COPY . .

# expose the port the app runs on
EXPOSE 5000

# run the application
CMD ["python", "app/app.py"]